### ISSUE TITLE
doTweenZoom

### ISSUE THREAD

**Issue by lazyremixmanordummyplayinggmod** [Meme1079/PsychWiki#11]
### What needs to be documented?

doTweenZoom(tag:String, vars:String, value:Dynamic, duration:Float, ease:String)

**Comment by MemeFlavor** [comment]
Thanks for reminding me this, don't know how I forgot about this function, but anyways it's now added back in the next update [yayayayyayaya](https://github.com/Meme1079/PsychWiki/blob/experimental-branch-thingy/PsychWiki_Source/Lua%20Script%20API/Tweens%20%26%20Timers%20Functions.md#dotweenzoomtagstring-varsstring-valuedynamic-durationfloat-easestring)
