### ISSUE TITLE
Wrong note ID on note tweens

### ISSUE THREAD

**Issue by Cappes** [Meme1079/PsychWiki#16]
### Describe your error here.

The defaultOpponentStrumX variables are inverted. 0 says it returns 428, but in game it returns 92.
This also happens for defaultPlayerStrumX in the wiki.

### The wiki function which you found the error

Strum Receptor/Character Variables
https://github.com/Meme1079/PsychWiki/wiki/Lua-Script-API:-Variables#strum-receptorcharacter-variables

**Comment by MemeFlavor** [comment]
fixed

https://github.com/Meme1079/PsychWiki/wiki/Lua-Script-API:-Variables#strum-receptorcharacter-variables:~:text=defaultOpponentStrumX0
