### ISSUE TITLE
A word Misspelled in the wiki

### ISSUE THREAD

**Issue by latterr** [Meme1079/PsychWiki#23]
### Describe your error here.

In the "Variables", the Deprecated Original Shortcut for downscroll is misspelled instead of getPropertyFromClass('ClientPrefs', 'downscroll')
It should be
getPropertyFromClass('ClientPrefs', 'downScroll')
Same thing with middlescroll

**Comment by MemeFlavor** [comment]
fixed: 
https://github.com/Meme1079/PsychWiki/blob/experimental-branch-thingy/PsychWiki_Source/Lua%20Script%20API/Variables.md#:~:text=Deprecated%20Original%20Shortcuts%3A-,downscroll,-%2D%20getPropertyFromClass(%27ClientPrefs
