### ISSUE TITLE
Flxanimate functions

### ISSUE THREAD

**Issue by lazyremixmanordummyplayinggmod** [Meme1079/PsychWiki#28]
### What type of suggestion you like?

New Page

### What suggestion you want on the PscyhWiki

Could be a new page or an addition to custom sprite and object functions

## FlxAnimate Functions
makeFlxAnimateSprite(tag:String, ?x:Float = 0, ?y:Float = 0, ?loadFolder:String = null)
similar to "makeAnimatedLuaSprite" but instead of a image loads a folder with sprite atlas inside

loadAnimateAtlas(tag:String, folderOrImg:Dynamic, ?spriteJson:Dynamic = null, ?animationJson:Dynamic = null)
loads a sprite atlas using image and the associated sprite json and animate json

addAnimationBySymbol(tag:String, name:String, symbol:String, ?framerate:Float = 24, ?loop:Bool = false, ?matX:Float = 0, ?matY:Float = 0)
addAnimationBySymbolIndices(tag:String, name:String, symbol:String, ?indices:Any = null, ?framerate:Float = 24, ?loop:Bool = false, ?matX:Float = 0, ?matY:Float = 0)
both are similar to the addAnimation function counterparts (Idk what matx and y is so you might need to test it out probably not needed)

**Comment by MemeFlavor** [comment]
Thanks for the suggestion, It's already being made but uhh in a WIP for a really long time. Cuz I don't know what the hell are parameters on these functions. Link: https://github.com/Meme1079/PsychWiki/commit/c28e789668f8efc35fa2a0f8d676706894328e41
