### ISSUE TITLE
need add text:Bool=true on getLuaObject() args

### ISSUE THREAD

**Issue by miujoan6952** [Meme1079/PsychWiki#29]
### What needs to be documented?

proof here: 
![getLuaObject](https://github.com/Meme1079/PsychWiki/assets/117433468/1d0fff08-e375-4424-b469-f38af2ee06fd)

**Comment by MemeFlavor** [comment]
Thanks for noticing

Fix: https://github.com/Meme1079/PsychWiki/wiki/Lua-Script-API:-HScript-Functions#getluaobjecttagstring-textbool--true
