### ISSUE TITLE
Language: getFileTranslation

### ISSUE THREAD

**Issue by unrealsunnydev** [Meme1079/PsychWiki#38]
## Describe your error here
I noticed that the usage of 'getFileTranslation' in the wiki is wrong and I would like to submit this correction suggestion.

### Languages: getFileTranslation(path:String)
This function is to find some "translatable" file and not a `.lang` file, such as:
```lua
function onCreate()
    makeLuaSprite('warn', '', 10, 10);
    loadGraphic('warn' getFileTranslation('images/warn'))
    addLuaSprite('warn')
end
```
Typically the path to this image is 'images/warn', but if you have a `.lang` file you can replace it:

```
// Warning Sprite
images/warn: "images/es-US/warn"
```

If there's anything wrong, tell me here or on my Discord (sunkydunky31)
See ya!

## The page that you find the error
https://github.com/Meme1079/PsychWiki/wiki/Lua-Script-API:-Language-Translation

**Comment by MemeFlavor** [comment]
So you're saying that the `getFileTranslation()` function gets the "translatable" from the `.lang` file. Like if the argument is `images/warn`, it tries to find it from a `.lang` file?

**Comment by unrealsunnydev** [comment]
No, it replaces files if any of its file paths are in a `.lang`, for example: Images and Audio.

**Comment by MemeFlavor** [comment]
> No, it replaces files if any of its file paths are in a `.lang`, for example: Images and Audio.

Basically if I have the file paths for any image or sounds inside a `.lang` file. It will replace it from the `.lang` file from the selected language.

**Comment by unrealsunnydev** [comment]
> > No, it replaces files if any of its file paths are in a `.lang`, for example: Images and Audio.
> 
> Basically if I have the file paths for any image or sounds inside a `.lang` file. It will replace it from the `.lang` file from the selected language.

Yes, that's right

**Comment by MemeFlavor** [comment]
> > > No, it replaces files if any of its file paths are in a `.lang`, for example: Images and Audio.
> > 
> > 
> > Basically if I have the file paths for any image or sounds inside a `.lang` file. It will replace it from the `.lang` file from the selected language.
> 
> Yes, that's right

Thanks for the report!
