### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by DaRealBoogy** [Meme1079/PsychWiki#5]
## What feature you want to add on the wiki?
The function name and the description or other stuff
troubleshooting page
a page or 2 dedicated to fixing errors
## What page you want to be added
Name of the Page
troubleshooting

**Comment by MemeFlavor** [comment]
Is it like a list of lua error and how to fix them??? I don't really know man, can you explain it in for more detail.

![image](https://github.com/Meme1079/PsychWiki/assets/101881784/79ab2fba-b4e1-4977-9e62-a4b99803dc72)

**Comment by DaRealBoogy** [comment]
yha, lua and compiling errors.

**Comment by MemeFlavor** [comment]
maybe i'll add it to the wiki on the next next update, but this is going to the "low priority" stuff for now
